org.gradle.jvmargs=-Xmx2g
org.gradle.configuration-cache=true
kotlin.code.style=official

# Override in ~/.gradle/gradle.properties or through ORG_GRADLE_PROJECT_* environment variables.
mavenCentralUsername=
mavenCentralPassword=
signingInMemoryKeyId=
signingInMemoryKeyPassword=
signingInMemoryKey=
