import { test } from 'node:test';
import assert from 'node:assert/strict';
import { apiMarkdown } from '../scripts/api-markdown';

test('keeps overload signatures, defaults and KDoc without Dokka controls', () => {
  const page = apiMarkdown(`<html><body><nav>Navigation</nav><div id="content">
    <div class="breadcrumbs">Prosa.kt/ExpressionScope/literal</div><h1>literal</h1>
    <button>Functions</button><span class="anchor-wrapper">Link copied to clipboard</span>
    <div class="symbol">fun literal(value: Any?, chain: ChainScope.() -&gt; Unit = {})</div>
    <div class="symbol">fun literal(value: Int, chain: ChainScope.() -&gt; Unit = {})</div>
    <p>Writes a <em>Kotlin literal</em>.</p>
    </div><footer>Generated by Dokka</footer></body></html>`, 'literal.html')!;
  assert.ok(page.markdown.startsWith('# Prosa.kt/ExpressionScope/literal'));
  assert.ok(page.markdown.includes('```kotlin\nfun literal(value: Any?, chain: ChainScope.() -> Unit = {})\n```'));
  assert.ok(page.markdown.includes('fun literal(value: Int,'));
  assert.ok(page.markdown.includes('Writes a _Kotlin literal_.'));
  assert.doesNotMatch(page.markdown, /Navigation|Functions|clipboard|Generated by/);
});

test('resolves inherited member links to Markdown and keeps external links', () => {
  const page = apiMarkdown(`<div id="content"><h1>FileScope</h1>
    <a href="../-declaration-container-scope/kt-class.html#overload">ktClass</a>
    <a href="https://kotlinlang.org/api/index.html">Kotlin</a></div>`,
    '-prosa.kt/com.alexstyl.prosakt/-file-scope/index.html')!;
  assert.ok(page.markdown.includes('[ktClass](/api/-prosa.kt/com.alexstyl.prosakt/-declaration-container-scope/kt-class.md)'));
  assert.ok(page.markdown.includes('[Kotlin](https://kotlinlang.org/api/index.html)'));
  assert.equal(apiMarkdown('<nav>Navigation only</nav>', 'navigation.html'), null);
});
